# This is a basic workflow to help you get started with Actions

name: Deploy prod on push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildAPI:
    # The type of runner that the job will run on
    name: Deploy IAM API
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get latest source
        uses: actions/checkout@v2
        
      - name: Stop Current API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
              cd /var/www/yatter.xyz/iam/dist/ && forever stop server.js
        
      - name: Deploy Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          rm: true
          source: "*"
          target: "${{ secrets.REMOTE_IAM_API_DIR }}"

      - name: Build API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
              cd /var/www/yatter.xyz/iam/ && npm i
              tsc && cd dist/ && forever start server.js
          
        
